name: SHIP-3D-SITE Actions Build Status

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x] # Test on LTS: Jod & Krypton

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch entire repository contents

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: |
          npm install
      - name: Security Audit
        run: |
          npm audit --audit-level=high
      - name: Check Lint
        run: |
          npm run lint
      - name: Run Tests
        run: |
          npm run test
      - name: Build Project
        run: |
          npm run build
